---
- name: GCC | Install Cern repo
  get_url: url=http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo dest=/etc/yum.repos.d/slc6-devtoolset.repo

- name: GCC | Copy RPMs
  copy: src={{ item }} dest=/tmp/RPMs/
  with_items:
    - files/compat-libgmp-4.3.1-1.sl7.x86_64.rpm
    - files/compat-libmpfr-2.4.1-1.sl7.x86_64.rpm

- name: GCC | Install dependencies
  sudo: yes 
  yum: name={{item}} state=present disable_gpg_check=yes
  with_items:
    - gcc
    - python-devel
    - /tmp/RPMs/compat-libgmp-4.3.1-1.sl7.x86_64.rpm
    - /tmp/RPMs/compat-libmpfr-2.4.1-1.sl7.x86_64.rpm
    - devtoolset-1.1-gcc-c++