---
- name: OpenEXR | Install dependencies
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - autoconf
    - automake
    - libtool

- name: OpenEXR | Download OpenEXR 
  get_url: url=https://github.com/openexr/openexr/archive/v2.2.0.tar.gz dest={{prefix_root}}/SOURCES/openexr-2.2.0.tar.gz

- name: OpenEXR | Extract OpenEXR Source
  unarchive: src="{{prefix_root}}/SOURCES/openexr-2.2.0.tar.gz" dest="{{prefix_root}}/SOURCES/" copy=no creates="{{prefix_root}}/SOURCES/openexr-2.2.0"

- name: OpenEXR | Build OpenEXR
  script: files/build_openexr.sh "{{prefix_root}}/SOURCES/openexr-2.2.0" "{{prefix_root}}/BUILDS/CY2015" creates="{{prefix_root}}/BUILDS/CY2015/openexr/2.2.0"
