---
- name: QT | Install Dependencies
  sudo: yes
  yum: name={{item}} state=present
  with_items:
    - libXext-devel
    - libXtst-devel
    - libX11-devel
    - mesa-libGL-devel
    - openssl-devel
    - gtk2-devel
    - gstreamer-devel
    - gstreamer1-plugins-base-devel
    - phonon-devel
    - libxcb 
    - libxcb-devel 
    - xcb-util 
    - xcb-util-devel
    - alsa-lib-devel


- name: QT | Download QT 
  get_url: url="https://download.qt.io/archive/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.tar.gz" dest="{{prefix_root}}/SOURCES/qt-everywhere-opensource-src-4.8.5.tar.gz"

- name: QT | Extract QT Source
  unarchive: src="{{prefix_root}}/SOURCES/qt-everywhere-opensource-src-4.8.5.tar.gz" dest="{{prefix_root}}/SOURCES/" copy=no creates="{{prefix_root}}/SOURCES/qt-everywhere-opensource-src-4.8.5"

- name: QT | Build QT
  script: files/build_qt.sh "{{prefix_root}}/SOURCES/qt-everywhere-opensource-src-4.8.5" "{{prefix_root}}/BUILDS/CY2015/qt/4.8.5" creates="{{prefix_root}}/BUILDS/CY2015/qt/4.8.5"