---
- name: Alembic | Download Alembic 
  get_url: url={{alembic_url}} dest={{alembic_archive_path}}

- name: Alembic | Extract Alembic Source
  unarchive: src={{alembic_archive_path}} dest="{{prefix_root}}/SOURCES/" copy=no creates="{{alembic_source_path}}"

- name: "Alembic | Build Alembic"
  script: build_alembic.sh creates={{alembic_prefix_path}}
  environment:
    ROOT: "{{alembic_source_path}}"
    PREFIX: "{{alembic_prefix_path}}"
    BOOST_PREFIX: "{{boost_prefix_path}}"
    ILMBASE_PREFIX: "{{ilmbase_prefix_path}}"
    OPENEXR_PREFIX: "{{openexr_prefix_path}}"
    OCIO_PREFIX: "{{ocio_prefix_path}}"
    PYTHON_PREFIX: "{{python_prefix_path}}"
    HDF5_PREFIX: "{{hdf5_prefix_path}}"