- name: Starting Build Process
  debug: msg="Building VFXLIB for {{ansible_distribution}}{{ansible_distribution_major_version}}"

- name: Create Directory Structure
  file: dest={{ item }} state=directory
  with_items:
  - "{{ prefix_root }}/SOURCES"
  - "{{ prefix_root }}/BUILDS/CY2014"
  - "{{ prefix_root }}/BUILDS/CY2015"

- include: gcc.yml
- include: python.yml
- include: qt.yml
- include: pyside.yml
- include: boost.yml
- include: openexr.yml
- include: ocio.yml
- include: oiio.yml
- include: hdf5.yml
- include: alembic.yml
- include: tbb.yml
- include: openvdb.yml
- include: fbx.yml
- name: Create Archive
  shell: shopt -s nullglob && tar -C {{prefix_root}}/BUILDS/CY2015 -zcvf /DATA/CY2015_{{ansible_distribution}}{{ansible_distribution_major_version}}.tar.gz .[^.]* ..?* * && shopt -u nullglob chdir="{{prefix_root}}/BUILDS/CY2015"
