---
- name: OCIO | Install dependencies
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - libjpeg-turbo-devel
    - libjpeg-turbo-static
    - libtiff-devel
    - libtiff-static
    - libpng-devel
    - libpng-static
    - glew-devel
    - freeglut-devel
    - libXmu-devel

- name: OCIO | Download OCIO 
  get_url: url={{ocio_url}} dest={{ocio_archive_path}}

- name: OCIO | Extract OCIO Source
  unarchive: src={{ocio_archive_path}} dest="{{prefix_root}}/SOURCES" copy=no creates={{ocio_source_path}}

- name: OCIO | Build OCIO
  script: build_ocio.sh creates={{ocio_prefix_path}}
  environment:
    ROOT: "{{ocio_source_path}}"
    PREFIX: "{{ocio_prefix_path}}"
    OCIO_BUILD_APPS: "OFF"
    OCIO_BUILD_SHARED: "OFF"
    OIIO_PREFIX: "{{oiio_prefix_path}}"
    PYTHON_PREFIX: "{{python_prefix_path}}"
    OCIO_BUILD_PYGLUE: "OFF"